              
[Unit]
Description=Prometheus server
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
Restart=on-failure
ExecStart=/usr/bin/prometheus \
        --config.file  /etc/prometheus/prometheus.yml \
        --config.tsdb.path  /etc/prometheus/data

[Install]
WantedBy=multi-user.target
